95 instances are sometimes wrong
GAIA-X4PLC-AAD/ontology-management-base pull request #111
Opened 2024-10-25 10:01 UTC by MircoNierenz

# Description

fix instance.json's
- remove shape in name
- media, requiredData, relatedData as lists
- remove duplicate link entries
- valid coordinates for georeference:BoundingBox/origin

## Type of change

Please delete options that are not relevant.

- [ ] New type (non-breaking change which adds a type)
- [x] Change (non-breaking change or fix on an existing type)
- [ ] Breaking change (Change that would cause existing Self Descriptions not to be accepted anymore by a Federated Catalogue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any
relevant details for your test configuration

- https://shacl.org/playground/
- provider-tools\jsonLD_validator

## Checklist

- [x] My code follows the modelling guidelines of this project
- [x] I have performed a self-review of my own changes

2024-10-25 12:50 UTC, MircoNierenz commented
add shape to name in @type to be valid with sh:closed = true for environment-model. 
I am working on the other jsonLDs now.

2024-11-05 10:13 UTC, lenasauermann requested changes

2024-11-05 10:13 UTC, lenasauermann commented on environment-model/environment-model_shacl.ttl
> +	sh:ignoredProperties ( rdf:type ) ;
komische Einrückungen

2024-11-05 10:13 UTC, lenasauermann commented on environment-model/environment-model_shacl.ttl
> +	sh:ignoredProperties ( rdf:type ) ;
markiere ich mal nur hier, ist aber an vielen Stellen der Fall

2024-11-07 11:12 UTC, MircoNierenz commented on environment-model/environment-model_shacl.ttl
> +	sh:ignoredProperties ( rdf:type ) ;
gefixt - im notepad++ war default tab eingestellt

2024-11-08 07:53 UTC, robertschubert requested changes
Nur eine Kleinigkeit, siehe Kommentar.

2024-11-08 07:53 UTC, robertschubert commented on georeference/georeference_shacl.ttl
> +
Bitte unnötige Leerzeile löschen

2024-11-08 08:18 UTC, MircoNierenz commented on georeference/georeference_shacl.ttl
> +
done!

2024-11-08 09:18 UTC, robertschubert approved these changes

2024-11-11 10:31 UTC, lenasauermann approved these changes

2024-11-14 07:45 UTC, robertschubert commented
2x approved - merge

2024-11-14 07:45 UTC, merged