fixed ontologies for general, georeference, hdmap and surface model
GAIA-X4PLC-AAD/ontology-management-base pull request #73
Opened 2024-07-02 09:54 UTC by lenasauermann

Added linked classes from shacl shape as ontology class. Also fixed a small error in georeference shacl.

I did it for general, georeference, hdmap and surface-model. I left scenario out as there are some linked classes, that only contain 1 attribute and therefore shouldn't be a sperate class.

2024-07-04 21:16 UTC, robertschubert commented
@lenasauermann  please check the failed pipeline and assign functional reviewers as well.

2024-07-04 21:17 UTC, robertschubert commented
> @lenasauermann please check the failed pipeline and assign functional reviewers as well.

I guess you need to merge main into this branch since there was a bugfix in the ci pipeline.

2024-07-17 08:59 UTC, robertschubert commented
> > @lenasauermann please check the failed pipeline and assign functional reviewers as well.
> 
> I guess you need to merge main into this branch since there was a bugfix in the ci pipeline.

I merged main into this branch. Pipelines are running now.

2024-07-17 09:02 UTC, robertschubert requested changes

2024-07-17 09:02 UTC, robertschubert commented on general/general_ontology.ttl
Please remove this line to have only 1 new line as separator

2024-07-17 09:02 UTC, robertschubert commented on georeference/georeference_ontology.ttl
> +
Please remove one line

2024-07-17 09:02 UTC, robertschubert commented on hdmap/hdmap_ontology.ttl
> +
Please remove one line

2024-07-17 09:02 UTC, robertschubert commented on hdmap/hdmap_ontology.ttl
> +
Please remove one line

2024-07-17 09:02 UTC, robertschubert commented on surface-model/surface-model_ontology.ttl
> +
Please remove one line

2024-07-25 08:57 UTC, robertschubert approved these changes
all fine for me now :)

2024-07-25 08:57 UTC, robertschubert commented
@lenasauermann  please assign a second reviewer

2024-07-25 11:37 UTC, jtdemer approved these changes
fine for me as well, thx lena and robert

2024-07-25 12:58 UTC, robertschubert commented
2 positive reviews, I will merge it.

2024-07-25 12:58 UTC, merged