87 missing shname und shproperty in properties with shnode
GAIA-X4PLC-AAD/ontology-management-base pull request #98
Opened 2024-09-08 13:32 UTC by MircoNierenz

# Description

add name and description to groups for all shacls

## Type of change

Please delete options that are not relevant.

- [ ] New type (non-breaking change which adds a type)
- [ ] Change (non-breaking change or fix on an existing type)
- [ ] Breaking change (Change that would cause existing Self Descriptions not to be accepted anymore by a Federated Catalogue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any
relevant details for your test configuration

- Test A
- Test B

## Checklist

- [ ] My code follows the modelling guidelines of this project
- [ ] I have performed a self-review of my own changes

2024-09-12 15:06 UTC, lenasauermann approved these changes

2024-09-13 07:29 UTC, robertschubert requested changes
See review remarks.
After this we need a merge from master or rebase to resolve the conflicts

2024-10-11 13:46 UTC, MircoNierenz commented on surface-model/surface-model_shacl.ttl
> +            sh:name "DataObject" ;
fixed in last commit

2024-10-11 13:47 UTC, MircoNierenz commented on environment-model/environment-model_shacl.ttl
> +            sh:name "generalObject" ;
change in last commit to "[name] object"

2024-10-11 13:53 UTC, lenasauermann approved these changes

2024-10-16 12:40 UTC, robertschubert commented
Pipeline is failing, I guess due to missing merge from master. 
I will resolve the conflicts.

2024-10-16 12:49 UTC, merged